version: "3.7"
services:
    redis:
        image: redis
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
